branch-defaults:
  default:
    environment: mkt-app-dev
    group_suffix: null
  master:
    environment: mkt-app-dev
environment-defaults:
  mkt-app-dev:
    branch: null
    repository: null
global:
  application_name: mkt_app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
